# Generated by Django 2.1 on 2018-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unmanned', '0003_auto_20181006_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='neededcall',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
