# Generated by Django 2.1.2 on 2018-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unmanned', '0004_auto_20181007_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorout',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
